[project]
authors = [
    { name = "Max Bernstein", email = "python@bernsteinbear.com" },
    { name = "Chris Gregory", email = "christopher.b.gregory@gmail.com" },
]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
description = "Scrapscript interpreter"
keywords = ["scrapscript", "interpreter"]
license = "MIT"
name = "scrapscript"
readme = "README.md"
version = "0.1.1"
requires-python = ">=3.8"

[project.urls]
repository = "https://github.com/tekknolagi/scrapscript"

[tool.uv]
dev-dependencies = ["mypy~=1.10.0", "pylint~=3.2.0", "ruff~=0.5.0", "pytest~=8.0.0"]

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pylint.basic]
good-names = ["i", "x"]
notes = ["FIXME"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
]

[tool.pylint.reports]
output-format = "colorized"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["E741"]

[tool.pytest.ini_options]
testpaths = ["."]
python_files = ["*_tests.py"]
addopts = "-v --tb=short"
