name: Stage app for PR preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  staging_app:
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: scrapscript-pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: scrapscript-pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        with:
          name: scrapscript-pr-${{ github.event.number }}
          region: ewr
          org: personal
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_DEPLOY_TOKEN }}
